name: R Package Validation Report
author: Roche
description: A Github Action that generates a validation report for an R package.

inputs:
  report_pkg_dir:
    description: Path to package's root.
    required: false
    default: "."
  report_output_prefix:
    description: >
      The output filename prefix for the validation report. If left blank,
      it defaults to the following convention:
      `<package name>-<package version>-validation-report`.
    required: false
    default: ""
  no_cache:
    description: "Disable github action R dependency caching"
    required: false
    default: "false"
  cache_version:
    description: "Version of the cache. To clean cache bump this version."
    required: false
    default: "v1"
  disable_install_dev_deps:
    description: |
      Disable installation of dev dependencies while
      building the report.
    required: false
    default: "false"
outputs:
  report_output_filename:
    description: Filename of the generated report.
    value: ${{ steps.report-generator.outputs.output-filename }}
branding: # https://feathericons.com/
  icon: "award"
  color: "blue"

runs:
  using: "composite"
  steps:
    - name: Get R version
      id: r_version
      run: echo "R_VERSION=$(R --version | head -1 | awk '{print $3}')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set R Library home on Linux
      run: |
        mkdir -p ${RUNNER_TEMP}/Library
        echo ".libPaths(c('${RUNNER_TEMP}/Library', .libPaths()))" > ~/.Rprofile
        cat ~/.Rprofile
      shell: bash

    - name: Cache R packages
      if: "contains(inputs.no_cache, 'false')"
      uses: actions/cache@v2
      with:
        path: /home/runner/work/_temp/Library
        key: ${{ inputs.cache_version }}-${{ runner.os }}-${{ steps.r_version.outputs.R_VERSION }}-${{ hashFiles('DESCRIPTION') }}
        restore-keys: ${{ inputs.cache_version }}-${{ runner.os }}-${{ steps.r_version.outputs.R_VERSION }}

    - name: Install dependencies
      run: |
        ${GITHUB_ACTION_PATH}/dependencies.R
      shell: bash

    - name: Run report generator
      id: report-generator
      run: |
        ${GITHUB_ACTION_PATH}/report-generator.R
        filename=$(basename $(cat /tmp/report_file_path.txt))
        echo "output-filename=${filename}" >> $GITHUB_OUTPUT
      shell: bash
      env:
        # Composite action doesn't set inputs as env vars.
        # We need to do this manually...
        INPUT_REPORT_PKG_DIR: ${{ inputs.report_pkg_dir }}
        INPUT_REPORT_OUTPUT_PREFIX: ${{ inputs.report_output_prefix }}
        DISABLE_INSTALL_DEV_DEPS: ${{ inputs.disable_install_dev_deps }}
